### ISSUE TITLE
Orientation of photos is wrong

### ISSUE THREAD

**Issue by nedrocks** [delphis-inc/delphis_app#88]
Platform: iOS

When uploading a photo, the orientation is wrong. Furthermore, when rotating the image it rotates to all orientations except the correct one.

**Comment by ywong137** [comment]
I went to try and upload the image here but apparently it was just a picture I took with my phone camera inline in the app so it didn't save the picture in my Camera Roll for upload.  It was a front-facing camera picture of my face, if it helps, and if you look in the threads where I contributed, you'll see it (a befuddled sideways picture of my face)

**Comment by nedrocks** [comment]
Reproduced this using my face cam on my phone. Cannot be done on sim as simulator does not simulate a camera.
